"""
VeriFlow — Chronological Forensics
Validates PDF metadata timestamps, timezone offsets, producer/creator
tool fingerprints, and temporal consistency.
"""
from __future__ import annotations

import re
from datetime import datetime
from typing import Optional

import pymupdf as fitz  # PyMuPDF 1.27+

from engine.models import (
    ChronologicalResult,
    MetadataFlag,
    Severity,
    Verdict,
)
from config import (
    EXPECTED_TIMEZONE_OFFSET,
    SUSPICIOUS_PRODUCERS,
    TRUSTED_PRODUCERS,
)


def _parse_pdf_date(date_str: str) -> tuple[Optional[datetime], Optional[str]]:
    """
    Parse PDF date format: D:YYYYMMDDHHmmSS+OO'oo' or variations.
    Returns (datetime, timezone_offset_string).
    """
    if not date_str:
        return None, None

    # Strip the D: prefix
    clean = date_str.strip()
    if clean.startswith("D:"):
        clean = clean[2:]

    # Extract timezone offset
    tz_match = re.search(r"([+-]\d{2}'\d{2}'|Z)$", clean)
    tz_offset = tz_match.group(0) if tz_match else None

    # Remove timezone for parsing
    if tz_offset:
        clean = clean[: -len(tz_offset)]

    # Pad to at least YYYYMMDD
    clean = clean.ljust(14, "0")

    try:
        dt = datetime.strptime(clean[:14], "%Y%m%d%H%M%S")
        return dt, tz_offset
    except (ValueError, IndexError):
        return None, tz_offset


def _check_timezone(tz_offset: Optional[str]) -> tuple[bool, Optional[str]]:
    """
    Validate that the timezone offset matches expected IST (+05'30').
    """
    if tz_offset is None:
        return False, None

    # Normalize for comparison
    normalized = tz_offset.replace(" ", "")
    expected = EXPECTED_TIMEZONE_OFFSET.replace(" ", "")

    return normalized == expected, normalized


def _check_producer_creator(
    producer: Optional[str], creator: Optional[str]
) -> tuple[bool, list[MetadataFlag]]:
    """
    Check if PDF producer/creator tools indicate editing software.
    """
    flags = []
    is_suspicious = False

    for field_name, value in [("Producer", producer), ("Creator", creator)]:
        if not value:
            continue

        lower_val = value.lower().strip()

        # Check against suspicious tools
        for tool in SUSPICIOUS_PRODUCERS:
            if tool in lower_val:
                is_suspicious = True
                flags.append(MetadataFlag(
                    field=field_name,
                    value=value,
                    expected="Government/Bank portal generator",
                    severity=Severity.HIGH,
                    description=(
                        f"{field_name} indicates editing tool '{value}'. "
                        f"Official documents should be generated by institutional "
                        f"systems, not desktop PDF editors."
                    ),
                ))
                break

        # Check if it matches trusted sources
        is_trusted = any(t in lower_val for t in TRUSTED_PRODUCERS)
        if is_trusted:
            flags.append(MetadataFlag(
                field=field_name,
                value=value,
                expected="Trusted source",
                severity=Severity.LOW,
                description=f"{field_name} matches known trusted generator: '{value}'.",
            ))

    return is_suspicious, flags


def _check_temporal_consistency(
    creation_dt: Optional[datetime],
    mod_dt: Optional[datetime],
) -> tuple[bool, list[MetadataFlag]]:
    """
    Check if modification date is suspiciously different from creation date.
    """
    flags = []

    if creation_dt is None or mod_dt is None:
        return True, flags

    if mod_dt < creation_dt:
        flags.append(MetadataFlag(
            field="ModDate",
            value=str(mod_dt),
            expected=f"After creation date ({creation_dt})",
            severity=Severity.CRITICAL,
            description=(
                f"Modification date ({mod_dt}) is BEFORE creation date "
                f"({creation_dt}). This is physically impossible and indicates "
                f"metadata manipulation."
            ),
        ))
        return False, flags

    delta = mod_dt - creation_dt
    if delta.days > 30:
        flags.append(MetadataFlag(
            field="ModDate",
            value=str(mod_dt),
            expected=f"Close to creation date ({creation_dt})",
            severity=Severity.HIGH,
            description=(
                f"Document modified {delta.days} days after creation. "
                f"Official documents are typically generated once. "
                f"Late modifications may indicate tampering."
            ),
        ))
        return False, flags
    elif delta.total_seconds() > 3600:  # > 1 hour
        flags.append(MetadataFlag(
            field="ModDate",
            value=str(mod_dt),
            expected=f"Same as or close to creation date ({creation_dt})",
            severity=Severity.MEDIUM,
            description=(
                f"Document modified {delta.total_seconds() / 3600:.1f} hours "
                f"after creation. Minor concern."
            ),
        ))

    return len(flags) == 0, flags


def analyze(file_path: str, document_name: str) -> ChronologicalResult:
    """
    Execute full chronological forensics on a PDF document.
    
    Validates timezone offsets against IST, checks producer/creator
    tool fingerprints, and verifies temporal consistency of metadata dates.
    """
    try:
        doc = fitz.open(file_path)
        meta = doc.metadata or {}
        doc.close()
    except Exception:
        return ChronologicalResult(
            document_name=document_name,
            timezone_valid=False,
            tool_suspicious=False,
            temporal_consistency=True,
            risk_score=0,
            verdict=Verdict.CLEAN,
        )

    # Extract raw dates
    raw_creation = meta.get("creationDate", "") or ""
    raw_mod = meta.get("modDate", "") or ""
    producer = meta.get("producer", "") or ""
    creator = meta.get("creator", "") or ""

    # Parse dates
    creation_dt, creation_tz = _parse_pdf_date(raw_creation)
    mod_dt, mod_tz = _parse_pdf_date(raw_mod)

    # 1. Timezone validation
    tz_valid_creation, tz_norm_creation = _check_timezone(creation_tz)
    tz_valid_mod, tz_norm_mod = _check_timezone(mod_tz)
    timezone_valid = tz_valid_creation or tz_valid_mod  # At least one should be IST

    tz_flags = []
    if raw_creation and not tz_valid_creation:
        tz_found = tz_norm_creation or "not specified"
        tz_flags.append(MetadataFlag(
            field="CreationDate Timezone",
            value=tz_found,
            expected=EXPECTED_TIMEZONE_OFFSET + " (IST)",
            severity=Severity.HIGH if tz_found != "not specified" else Severity.MEDIUM,
            description=(
                f"Creation date timezone is '{tz_found}', expected IST "
                f"({EXPECTED_TIMEZONE_OFFSET}). Documents from Indian institutions "
                f"should have IST timezone."
            ),
        ))

    # 2. Producer/Creator analysis
    tool_suspicious, tool_flags = _check_producer_creator(producer, creator)

    # 3. Temporal consistency
    temporal_consistent, temporal_flags = _check_temporal_consistency(creation_dt, mod_dt)

    # Aggregate flags
    all_flags = tz_flags + tool_flags + temporal_flags

    # Calculate risk score
    score = 0
    for flag in all_flags:
        if flag.severity == Severity.CRITICAL:
            score += 35
        elif flag.severity == Severity.HIGH:
            score += 20
        elif flag.severity == Severity.MEDIUM:
            score += 10
        elif flag.severity == Severity.LOW:
            score += 0  # Info only

    risk_score = min(100.0, score)

    if risk_score >= 60:
        verdict = Verdict.TAMPERED
    elif risk_score >= 25:
        verdict = Verdict.SUSPICIOUS
    else:
        verdict = Verdict.CLEAN

    return ChronologicalResult(
        document_name=document_name,
        creation_date=str(creation_dt) if creation_dt else raw_creation or None,
        modification_date=str(mod_dt) if mod_dt else raw_mod or None,
        producer=producer or None,
        creator=creator or None,
        timezone_valid=timezone_valid,
        timezone_found=tz_norm_creation or tz_norm_mod,
        tool_suspicious=tool_suspicious,
        metadata_flags=all_flags,
        temporal_consistency=temporal_consistent,
        risk_score=round(risk_score, 2),
        verdict=verdict,
    )
